### ISSUE TITLE
Maven POM not correctly scanned

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-xml-plugin#1] opened 2016-09-25 09:31 UTC
Currently we are not able to scan the Maven POM of the RDBMS plugin correctly. I set the tag `mark-repository-element-not-scanable` in the repository of the RDBMS plugin to mark the affected code.

Because of the incomplete/incorrect scan we following query has always an empty result set:

```
MATCH (rp:RootProject)-[:HAS_MODEL]->(m:Xml:Pom:Maven)
          -[:HAS_ROOT_ELEMENT]->(rootElement:Element:Xml)
          -[:HAS_ELEMENT]->(reps:Element:Xml {name: "repositories"})
          -[:HAS_ELEMENT]->(r:Xml:Element {name: "repository"})
          -[:HAS_ELEMENT]->(url:Xml:Element)
          -[:HAS_TEXT]->(t:Text:Xml {
                 value: "https://oss.sonatype.org/content/repositories/snapshots"}
           )
WITH r

MATCH (r)-[:HAS_ELEMENT]->(s:Xml:Element {name: "snapshots"})
                -[:HAS_ELEMENT]->(e:Xml:Element)-[:HAS_TEXT]->(v:Xml:Text {value: 'true'})
RETURN r
```

If I revoke all plugin related sections the scan will find all nodes and the query succeeds. 

Actually this is a strange problem as this problem does not occure for other projects.

**Comment by DirkMahler** [comment] 2024-07-04 08:39
Cannot reproduce the issue, closing this ticket.

**Closed as completed by DirkMahler** 2024-07-04 08:39 UTC
Labels: type:bug
